services:
  - type: web
    name: splitshare-backend
    env: node
    buildCommand: npm install
    startCommand: npm run dev:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
